In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
x = df.iloc[:,3:10].values
y = df.iloc[:,10].values

In [4]:
x

array([[619, 'France', 'Female', ..., 2, 0.0, 1],
       [608, 'Spain', 'Female', ..., 1, 83807.86, 1],
       [502, 'France', 'Female', ..., 8, 159660.8, 3],
       ...,
       [709, 'France', 'Female', ..., 7, 0.0, 1],
       [772, 'Germany', 'Male', ..., 3, 75075.31, 2],
       [792, 'France', 'Female', ..., 4, 130142.79, 1]], dtype=object)

## Encoding Categorical Variable

In [5]:
from sklearn.preprocessing import LabelEncoder
label_x_1 = LabelEncoder()
x[:,1] = label_x_1.fit_transform(x[:,1])

In [6]:
x

array([[619, 0, 'Female', ..., 2, 0.0, 1],
       [608, 2, 'Female', ..., 1, 83807.86, 1],
       [502, 0, 'Female', ..., 8, 159660.8, 3],
       ...,
       [709, 0, 'Female', ..., 7, 0.0, 1],
       [772, 1, 'Male', ..., 3, 75075.31, 2],
       [792, 0, 'Female', ..., 4, 130142.79, 1]], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
label_x_2 = LabelEncoder()
x[:,2] = label_x_2.fit_transform(x[:,2])

In [8]:
x

array([[619, 0, 0, ..., 2, 0.0, 1],
       [608, 2, 0, ..., 1, 83807.86, 1],
       [502, 0, 0, ..., 8, 159660.8, 3],
       ...,
       [709, 0, 0, ..., 7, 0.0, 1],
       [772, 1, 1, ..., 3, 75075.31, 2],
       [792, 0, 0, ..., 4, 130142.79, 1]], dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[1])
x = onehotencoder.fit_transform(x).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
x = x[:,1:]

In [11]:
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 2.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 1.0000000e+00,
        8.3807860e+04, 1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 8.0000000e+00,
        1.5966080e+05, 3.0000000e+00],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 7.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 3.0000000e+00,
        7.5075310e+04, 2.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 4.0000000e+00,
        1.3014279e+05, 1.0000000e+00]])

In [12]:
#onehotencoder = OneHotEncoder(categories='auto')
#x = onehotencoder.fit_transform(x).toarray()

In [13]:
#x = x[:,1:]

In [14]:
#x

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

## ANN Part

In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [18]:
model = Sequential()

## First Input Layer

In [19]:
model.add(Dense(activation='relu',input_dim=8, units=6,kernel_initializer='uniform'))

## Second Input Layer

In [20]:
model.add(Dense(activation='relu', units=6,kernel_initializer='uniform'))

## Output Layer

In [21]:
model.add(Dense(activation='sigmoid', units=1, kernel_initializer='uniform'))

## Compiling The ANN

In [22]:
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [28]:
model.fit(x_train,y_train, batch_size=10, nb_epoch=100)

Epoch 1/100
1270/8000 [===>..........................] - ETA: 0s - loss: 0.5975 - accuracy: 0.7157

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 1s 108us/step - loss: 0.6015 - accuracy: 0.7078
Epoch 2/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.6016 - accuracy: 0.7078
Epoch 3/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.6016 - accuracy: 0.7078
Epoch 4/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.6015 - accuracy: 0.7078
Epoch 5/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.6016 - accuracy: 0.7078
Epoch 6/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.6013 - accuracy: 0.7078
Epoch 7/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.6017 - accuracy: 0.7078
Epoch 8/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.6017 - accuracy: 0.7078
Epoch 9/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.6016 - accuracy: 0.7078
Epoch 10/100
8000/8000 [==============================] - 1s 107us/

8000/8000 [==============================] - 1s 105us/step - loss: 0.6016 - accuracy: 0.7078
Epoch 79/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.6014 - accuracy: 0.7078
Epoch 80/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.6015 - accuracy: 0.7078
Epoch 81/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.6014 - accuracy: 0.7078
Epoch 82/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.6014 - accuracy: 0.7078
Epoch 83/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.6014 - accuracy: 0.7078
Epoch 84/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.6013 - accuracy: 0.7078
Epoch 85/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.6013 - accuracy: 0.7078
Epoch 86/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.6015 - accuracy: 0.7078
Epoch 87/100
8000/8000 [==============================] - 1

In [29]:
y_pred = model.predict(x_test)

In [30]:
y_pred

array([[0.72550845],
       [0.68669784],
       [0.6769818 ],
       ...,
       [0.6934931 ],
       [0.73239267],
       [0.7729397 ]], dtype=float32)

In [31]:
y_pred = (y_pred > .5)
y_pred

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [32]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
cm

array([[   0,    0],
       [ 607, 1393]], dtype=int64)

In [34]:
pip install --upgrade tensorflow

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an EnvironmentError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Jewel\\AppData\\Local\\Temp\\pip-unpack-1q0a87e6\\tensorflow-2.1.0-cp37-cp37m-win_amd64.whl'
Consider using the `--user` option or check the permissions.

